version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    steps:
      - run:
          name: Create test-results directory
          command: mkdir -p /tmp/test-results
      - run:
          name: Generate some artifact
          command: echo "Hello, world!" > /tmp/test-results/artifact.txt
      - run:
          name: Generate test results
          command: |
            echo '<testsuites>
            <testsuite tests="2" failures="1" time="0.005" name="_/tmp/go">
            <properties>
            <property name="go.version" value="go1.9.2"/>
            </properties>
            <testcase classname="go" name="TestSimple" time="0.000"/>
            <testcase classname="go" name="TestFail" time="0.000">
            <failure message="Failed" type="">asdf_test.go:12: Doh</failure>
            </testcase>
            </testsuite>
            </testsuites>' > /tmp/test-results/report.xml
      - store_artifacts:
          path: /tmp/test-results
      - store_test_results:
          path: /tmp/test-results