version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: Create artifact directory
          command: mkdir artifacts
      - run:
          name: Generate some artifact
          command: echo "Hello, world!" > artifacts/artifact.txt
      - store_artifacts:
          path: artifacts/

workflows:
  version: 2
  btd:
    jobs:
      - build
